export interface Theme {
  name: string;
  colors: {
    '--bg-primary': string;
    '--bg-secondary': string;
    '--bg-tertiary': string;
    '--bg-content': string;
    '--bg-accent-primary': string;
    '--bg-accent-primary-hover': string;
    '--bg-success': string;
    '--bg-error': string;
    '--bg-warning': string;
    '--text-primary': string;
    '--text-secondary': string;
    '--text-tertiary': string;
    '--text-content-primary': string;
    '--text-content-secondary': string;
    '--text-on-accent': string;
    '--text-success': string;
    '--text-error': string;
    '--text-warning': string;
    '--border-primary': string;
    '--border-secondary': string;
    '--border-content': string;
    '--scrollbar-track': string;
    '--scrollbar-thumb': string;
    '--scrollbar-thumb-hover': string;
  };
}

export const THEMES: Theme[] = [
  {
    name: 'Default Dark',
    colors: {
        '--bg-primary': '#0f172a',
        '--bg-secondary': '#1e293b',
        '--bg-tertiary': '#334155',
        '--bg-content': '#ffffff',
        '--bg-accent-primary': '#3b82f6',
        '--bg-accent-primary-hover': '#2563eb',
        '--bg-success': '#16a34a',
        '--bg-error': '#dc2626',
        '--bg-warning': '#f59e0b',
        '--text-primary': '#e2e8f0',
        '--text-secondary': '#94a3b8',
        '--text-tertiary': '#64748b',
        '--text-content-primary': '#1e293b',
        '--text-content-secondary': '#475569',
        '--text-on-accent': '#ffffff',
        '--text-success': '#22c55e',
        '--text-error': '#ef4444',
        '--text-warning': '#f59e0b',
        '--border-primary': '#334155',
        '--border-secondary': '#475569',
        '--border-content': '#e2e8f0',
        '--scrollbar-track': '#1e293b',
        '--scrollbar-thumb': '#475569',
        '--scrollbar-thumb-hover': '#64748b',
    },
  },
  {
    name: 'Abyss',
    colors: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#0b0f19',
      '--bg-tertiary': '#161b29',
      '--bg-content': '#10141f',
      '--bg-accent-primary': '#007bff',
      '--bg-accent-primary-hover': '#0056b3',
      '--bg-success': '#28a745',
      '--bg-error': '#dc3545',
      '--bg-warning': '#ffc107',
      '--text-primary': '#e8eaed',
      '--text-secondary': '#bdc1c6',
      '--text-tertiary': '#80868b',
      '--text-content-primary': '#e8eaed',
      '--text-content-secondary': '#bdc1c6',
      '--text-on-accent': '#ffffff',
      '--text-success': '#28a745',
      '--text-error': '#dc3545',
      '--text-warning': '#ffc107',
      '--border-primary': '#1f2430',
      '--border-secondary': '#2e3440',
      '--border-content': '#1f2430',
      '--scrollbar-track': '#0b0f19',
      '--scrollbar-thumb': '#161b29',
      '--scrollbar-thumb-hover': '#1f2430',
    },
  },
  {
    name: 'Forest',
    colors: {
      '--bg-primary': '#1a2a1a',
      '--bg-secondary': '#2a3a2a',
      '--bg-tertiary': '#3a4a3a',
      '--bg-content': '#f0fff0',
      '--bg-accent-primary': '#6B8E23',
      '--bg-accent-primary-hover': '#556B2F',
      '--bg-success': '#2E8B57',
      '--bg-error': '#B22222',
      '--bg-warning': '#FFD700',
      '--text-primary': '#f0fff0',
      '--text-secondary': '#b0d9b0',
      '--text-tertiary': '#93b993',
      '--text-content-primary': '#006400',
      '--text-content-secondary': '#228B22',
      '--text-on-accent': '#ffffff',
      '--text-success': '#2E8B57',
      '--text-error': '#B22222',
      '--text-warning': '#DAA520',
      '--border-primary': '#3a4a3a',
      '--border-secondary': '#4a5a4a',
      '--border-content': '#d0e0d0',
      '--scrollbar-track': '#2a3a2a',
      '--scrollbar-thumb': '#3a4a3a',
      '--scrollbar-thumb-hover': '#4a5a4a',
    },
  },
  {
    name: 'Sunset',
    colors: {
      '--bg-primary': '#2c1e3e',
      '--bg-secondary': '#4a2f58',
      '--bg-tertiary': '#674172',
      '--bg-content': '#fff0f5',
      '--bg-accent-primary': '#ff7e5f',
      '--bg-accent-primary-hover': '#feb47b',
      '--bg-success': '#32cd32',
      '--bg-error': '#ff4500',
      '--bg-warning': '#ffa500',
      '--text-primary': '#f5e6ff',
      '--text-secondary': '#d9b3ff',
      '--text-tertiary': '#be80ff',
      '--text-content-primary': '#4a0e4e',
      '--text-content-secondary': '#800080',
      '--text-on-accent': '#ffffff',
      '--text-success': '#32cd32',
      '--text-error': '#ff4500',
      '--text-warning': '#ffa500',
      '--border-primary': '#674172',
      '--border-secondary': '#84538c',
      '--border-content': '#ffdfeb',
      '--scrollbar-track': '#4a2f58',
      '--scrollbar-thumb': '#674172',
      '--scrollbar-thumb-hover': '#84538c',
    },
  },
  {
    name: 'Arctic',
    colors: {
      '--bg-primary': '#f0f8ff',
      '--bg-secondary': '#e6f2ff',
      '--bg-tertiary': '#d9ecff',
      '--bg-content': '#ffffff',
      '--bg-accent-primary': '#00bfff',
      '--bg-accent-primary-hover': '#1e90ff',
      '--bg-success': '#8fbc8f',
      '--bg-error': '#f08080',
      '--bg-warning': '#ffd700',
      '--text-primary': '#00008b',
      '--text-secondary': '#4682b4',
      '--text-tertiary': '#708090',
      '--text-content-primary': '#2f4f4f',
      '--text-content-secondary': '#778899',
      '--text-on-accent': '#ffffff',
      '--text-success': '#2e8b57',
      '--text-error': '#cd5c5c',
      '--text-warning': '#b8860b',
      '--border-primary': '#d9ecff',
      '--border-secondary': '#b0c4de',
      '--border-content': '#d3d3d3',
      '--scrollbar-track': '#e6f2ff',
      '--scrollbar-thumb': '#d9ecff',
      '--scrollbar-thumb-hover': '#b0c4de',
    },
  },
  {
    name: 'Sakura',
    colors: {
      '--bg-primary': '#fff0f5',
      '--bg-secondary': '#ffe4e1',
      '--bg-tertiary': '#ffc0cb',
      '--bg-content': '#ffffff',
      '--bg-accent-primary': '#ff69b4',
      '--bg-accent-primary-hover': '#ff1493',
      '--bg-success': '#98fb98',
      '--bg-error': '#db7093',
      '--bg-warning': '#f0e68c',
      '--text-primary': '#8b4513',
      '--text-secondary': '#a0522d',
      '--text-tertiary': '#cd853f',
      '--text-content-primary': '#5d3b1a',
      '--text-content-secondary': '#8b5a2b',
      '--text-on-accent': '#ffffff',
      '--text-success': '#2e8b57',
      '--text-error': '#c71585',
      '--text-warning': '#b8860b',
      '--border-primary': '#ffc0cb',
      '--border-secondary': '#ffb6c1',
      '--border-content': '#f5f5f5',
      '--scrollbar-track': '#ffe4e1',
      '--scrollbar-thumb': '#ffc0cb',
      '--scrollbar-thumb-hover': '#ffb6c1',
    },
  },
  {
    name: 'Cyberpunk',
    colors: {
      '--bg-primary': '#0c002b',
      '--bg-secondary': '#1a004a',
      '--bg-tertiary': '#28006b',
      '--bg-content': '#000000',
      '--bg-accent-primary': '#ff00ff',
      '--bg-accent-primary-hover': '#c700c7',
      '--bg-success': '#00ff00',
      '--bg-error': '#ff0000',
      '--bg-warning': '#ffff00',
      '--text-primary': '#00ffff',
      '--text-secondary': '#80ffff',
      '--text-tertiary': '#c0ffff',
      '--text-content-primary': '#ffffff',
      '--text-content-secondary': '#e0e0e0',
      '--text-on-accent': '#ffffff',
      '--text-success': '#00ff00',
      '--text-error': '#ff0000',
      '--text-warning': '#ffff00',
      '--border-primary': '#28006b',
      '--border-secondary': '#36008b',
      '--border-content': '#28006b',
      '--scrollbar-track': '#1a004a',
      '--scrollbar-thumb': '#28006b',
      '--scrollbar-thumb-hover': '#36008b',
    },
  },
  {
    name: 'Dracula',
    colors: {
      '--bg-primary': '#282a36',
      '--bg-secondary': '#383a59',
      '--bg-tertiary': '#44475a',
      '--bg-content': '#282a36',
      '--bg-accent-primary': '#bd93f9',
      '--bg-accent-primary-hover': '#aa83e8',
      '--bg-success': '#50fa7b',
      '--bg-error': '#ff5555',
      '--bg-warning': '#f1fa8c',
      '--text-primary': '#f8f8f2',
      '--text-secondary': '#bd93f9',
      '--text-tertiary': '#6272a4',
      '--text-content-primary': '#f8f8f2',
      '--text-content-secondary': '#e0e0e0',
      '--text-on-accent': '#282a36',
      '--text-success': '#50fa7b',
      '--text-error': '#ff5555',
      '--text-warning': '#f1fa8c',
      '--border-primary': '#44475a',
      '--border-secondary': '#6272a4',
      '--border-content': '#44475a',
      '--scrollbar-track': '#383a59',
      '--scrollbar-thumb': '#44475a',
      '--scrollbar-thumb-hover': '#6272a4',
    },
  },
  {
    name: 'Solarized Light',
    colors: {
      '--bg-primary': '#fdf6e3',
      '--bg-secondary': '#eee8d5',
      '--bg-tertiary': '#93a1a1',
      '--bg-content': '#ffffff',
      '--bg-accent-primary': '#268bd2',
      '--bg-accent-primary-hover': '#1a6a9e',
      '--bg-success': '#859900',
      '--bg-error': '#dc322f',
      '--bg-warning': '#b58900',
      '--text-primary': '#002b36',
      '--text-secondary': '#586e75',
      '--text-tertiary': '#657b83',
      '--text-content-primary': '#002b36',
      '--text-content-secondary': '#586e75',
      '--text-on-accent': '#ffffff',
      '--text-success': '#859900',
      '--text-error': '#dc322f',
      '--text-warning': '#b58900',
      '--border-primary': '#93a1a1',
      '--border-secondary': '#839496',
      '--border-content': '#eee8d5',
      '--scrollbar-track': '#eee8d5',
      '--scrollbar-thumb': '#93a1a1',
      '--scrollbar-thumb-hover': '#839496',
    },
  },
   {
    name: 'Solarized Dark',
    colors: {
      '--bg-primary': '#002b36',
      '--bg-secondary': '#073642',
      '--bg-tertiary': '#586e75',
      '--bg-content': '#002b36',
      '--bg-accent-primary': '#268bd2',
      '--bg-accent-primary-hover': '#1a6a9e',
      '--bg-success': '#859900',
      '--bg-error': '#dc322f',
      '--bg-warning': '#b58900',
      '--text-primary': '#fdf6e3',
      '--text-secondary': '#93a1a1',
      '--text-tertiary': '#839496',
      '--text-content-primary': '#fdf6e3',
      '--text-content-secondary': '#eee8d5',
      '--text-on-accent': '#ffffff',
      '--text-success': '#859900',
      '--text-error': '#dc322f',
      '--text-warning': '#b58900',
      '--border-primary': '#586e75',
      '--border-secondary': '#657b83',
      '--border-content': '#073642',
      '--scrollbar-track': '#073642',
      '--scrollbar-thumb': '#586e75',
      '--scrollbar-thumb-hover': '#657b83',
    },
  },
  {
    name: 'Nord',
    colors: {
      '--bg-primary': '#2e3440',
      '--bg-secondary': '#3b4252',
      '--bg-tertiary': '#434c5e',
      '--bg-content': '#2e3440',
      '--bg-accent-primary': '#88c0d0',
      '--bg-accent-primary-hover': '#7aacc0',
      '--bg-success': '#a3be8c',
      '--bg-error': '#bf616a',
      '--bg-warning': '#ebcb8b',
      '--text-primary': '#d8dee9',
      '--text-secondary': '#e5e9f0',
      '--text-tertiary': '#eceff4',
      '--text-content-primary': '#d8dee9',
      '--text-content-secondary': '#e5e9f0',
      '--text-on-accent': '#2e3440',
      '--text-success': '#a3be8c',
      '--text-error': '#bf616a',
      '--text-warning': '#ebcb8b',
      '--border-primary': '#434c5e',
      '--border-secondary': '#4c566a',
      '--border-content': '#3b4252',
      '--scrollbar-track': '#3b4252',
      '--scrollbar-thumb': '#434c5e',
      '--scrollbar-thumb-hover': '#4c566a',
    },
  },
  {
    name: 'Monokai',
    colors: {
      '--bg-primary': '#272822',
      '--bg-secondary': '#3e3d32',
      '--bg-tertiary': '#75715e',
      '--bg-content': '#272822',
      '--bg-accent-primary': '#f92672',
      '--bg-accent-primary-hover': '#d92060',
      '--bg-success': '#a6e22e',
      '--bg-error': '#f92672',
      '--bg-warning': '#e6db74',
      '--text-primary': '#f8f8f2',
      '--text-secondary': '#a6e22e',
      '--text-tertiary': '#75715e',
      '--text-content-primary': '#f8f8f2',
      '--text-content-secondary': '#e0e0e0',
      '--text-on-accent': '#ffffff',
      '--text-success': '#a6e22e',
      '--text-error': '#f92672',
      '--text-warning': '#e6db74',
      '--border-primary': '#75715e',
      '--border-secondary': '#9e9a89',
      '--border-content': '#3e3d32',
      '--scrollbar-track': '#3e3d32',
      '--scrollbar-thumb': '#75715e',
      '--scrollbar-thumb-hover': '#9e9a89',
    },
  },
  {
    name: 'Gruvbox Dark',
    colors: {
      '--bg-primary': '#282828',
      '--bg-secondary': '#3c3836',
      '--bg-tertiary': '#504945',
      '--bg-content': '#1d2021',
      '--bg-accent-primary': '#fabd2f',
      '--bg-accent-primary-hover': '#d5a021',
      '--bg-success': '#b8bb26',
      '--bg-error': '#fb4934',
      '--bg-warning': '#fe8019',
      '--text-primary': '#ebdbb2',
      '--text-secondary': '#d5c4a1',
      '--text-tertiary': '#bdae93',
      '--text-content-primary': '#ebdbb2',
      '--text-content-secondary': '#d5c4a1',
      '--text-on-accent': '#282828',
      '--text-success': '#b8bb26',
      '--text-error': '#fb4934',
      '--text-warning': '#fe8019',
      '--border-primary': '#504945',
      '--border-secondary': '#665c54',
      '--border-content': '#3c3836',
      '--scrollbar-track': '#3c3836',
      '--scrollbar-thumb': '#504945',
      '--scrollbar-thumb-hover': '#665c54',
    },
  },
   {
    name: 'Rose Pine',
    colors: {
      '--bg-primary': '#191724',
      '--bg-secondary': '#1f1d2e',
      '--bg-tertiary': '#26233a',
      '--bg-content': '#191724',
      '--bg-accent-primary': '#eb6f92',
      '--bg-accent-primary-hover': '#c95f7e',
      '--bg-success': '#9ccfd8',
      '--bg-error': '#eb6f92',
      '--bg-warning': '#f6c177',
      '--text-primary': '#e0def4',
      '--text-secondary': '#908caa',
      '--text-tertiary': '#6e6a86',
      '--text-content-primary': '#e0def4',
      '--text-content-secondary': '#c5c3e0',
      '--text-on-accent': '#191724',
      '--text-success': '#9ccfd8',
      '--text-error': '#eb6f92',
      '--text-warning': '#f6c177',
      '--border-primary': '#26233a',
      '--border-secondary': '#3f3c55',
      '--border-content': '#1f1d2e',
      '--scrollbar-track': '#1f1d2e',
      '--scrollbar-thumb': '#26233a',
      '--scrollbar-thumb-hover': '#3f3c55',
    },
  },
  {
    name: 'Coffee',
    colors: {
      '--bg-primary': '#21171a',
      '--bg-secondary': '#3d2f2f',
      '--bg-tertiary': '#5a4747',
      '--bg-content': '#f5e8de',
      '--bg-accent-primary': '#c7a17a',
      '--bg-accent-primary-hover': '#b08e6a',
      '--bg-success': '#7a9c7a',
      '--bg-error': '#d96a6a',
      '--bg-warning': '#e6b87d',
      '--text-primary': '#dcdcdc',
      '--text-secondary': '#b0a0a0',
      '--text-tertiary': '#8c7b7b',
      '--text-content-primary': '#3a2d2d',
      '--text-content-secondary': '#5a4747',
      '--text-on-accent': '#21171a',
      '--text-success': '#7a9c7a',
      '--text-error': '#d96a6a',
      '--text-warning': '#e6b87d',
      '--border-primary': '#5a4747',
      '--border-secondary': '#776060',
      '--border-content': '#e0d0c0',
      '--scrollbar-track': '#3d2f2f',
      '--scrollbar-thumb': '#5a4747',
      '--scrollbar-thumb-hover': '#776060',
    },
  },
  {
    name: 'Ocean',
    colors: {
      '--bg-primary': '#0f2027',
      '--bg-secondary': '#203a43',
      '--bg-tertiary': '#2c5364',
      '--bg-content': '#ffffff',
      '--bg-accent-primary': '#1488cc',
      '--bg-accent-primary-hover': '#2b32b2',
      '--bg-success': '#43a047',
      '--bg-error': '#e53935',
      '--bg-warning': '#fdd835',
      '--text-primary': '#e0f7fa',
      '--text-secondary': '#b2ebf2',
      '--text-tertiary': '#80deea',
      '--text-content-primary': '#0f2027',
      '--text-content-secondary': '#2c5364',
      '--text-on-accent': '#ffffff',
      '--text-success': '#43a047',
      '--text-error': '#e53935',
      '--text-warning': '#fdd835',
      '--border-primary': '#2c5364',
      '--border-secondary': '#3e6a7e',
      '--border-content': '#e0f7fa',
      '--scrollbar-track': '#203a43',
      '--scrollbar-thumb': '#2c5364',
      '--scrollbar-thumb-hover': '#3e6a7e',
    },
  },
  {
    name: 'Matrix',
    colors: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#0d0d0d',
      '--bg-tertiary': '#1a1a1a',
      '--bg-content': '#000000',
      '--bg-accent-primary': '#00ff00',
      '--bg-accent-primary-hover': '#00e600',
      '--bg-success': '#00ff00',
      '--bg-error': '#ff0000',
      '--bg-warning': '#ffff00',
      '--text-primary': '#00ff00',
      '--text-secondary': '#00e600',
      '--text-tertiary': '#00b300',
      '--text-content-primary': '#00ff00',
      '--text-content-secondary': '#00cc00',
      '--text-on-accent': '#000000',
      '--text-success': '#00ff00',
      '--text-error': '#ff0000',
      '--text-warning': '#ffff00',
      '--border-primary': '#1a1a1a',
      '--border-secondary': '#333333',
      '--border-content': '#1a1a1a',
      '--scrollbar-track': '#0d0d0d',
      '--scrollbar-thumb': '#1a1a1a',
      '--scrollbar-thumb-hover': '#333333',
    },
  },
  {
    name: 'High Contrast Light',
    colors: {
      '--bg-primary': '#ffffff',
      '--bg-secondary': '#f0f0f0',
      '--bg-tertiary': '#e0e0e0',
      '--bg-content': '#ffffff',
      '--bg-accent-primary': '#0000ff',
      '--bg-accent-primary-hover': '#0000cc',
      '--bg-success': '#008000',
      '--bg-error': '#ff0000',
      '--bg-warning': '#ffa500',
      '--text-primary': '#000000',
      '--text-secondary': '#1a1a1a',
      '--text-tertiary': '#333333',
      '--text-content-primary': '#000000',
      '--text-content-secondary': '#1a1a1a',
      '--text-on-accent': '#ffffff',
      '--text-success': '#008000',
      '--text-error': '#ff0000',
      '--text-warning': '#ffa500',
      '--border-primary': '#cccccc',
      '--border-secondary': '#b3b3b3',
      '--border-content': '#d9d9d9',
      '--scrollbar-track': '#f0f0f0',
      '--scrollbar-thumb': '#e0e0e0',
      '--scrollbar-thumb-hover': '#cccccc',
    },
  },
  {
    name: 'High Contrast Dark',
    colors: {
      '--bg-primary': '#000000',
      '--bg-secondary': '#1a1a1a',
      '--bg-tertiary': '#333333',
      '--bg-content': '#000000',
      '--bg-accent-primary': '#ffff00',
      '--bg-accent-primary-hover': '#e6e600',
      '--bg-success': '#00ff00',
      '--bg-error': '#ff00ff',
      '--bg-warning': '#00ffff',
      '--text-primary': '#ffffff',
      '--text-secondary': '#f0f0f0',
      '--text-tertiary': '#e0e0e0',
      '--text-content-primary': '#ffffff',
      '--text-content-secondary': '#f0f0f0',
      '--text-on-accent': '#000000',
      '--text-success': '#00ff00',
      '--text-error': '#ff00ff',
      '--text-warning': '#00ffff',
      '--border-primary': '#333333',
      '--border-secondary': '#4d4d4d',
      '--border-content': '#333333',
      '--scrollbar-track': '#1a1a1a',
      '--scrollbar-thumb': '#333333',
      '--scrollbar-thumb-hover': '#4d4d4d',
    },
  },
  {
    name: 'Crimson',
    colors: {
      '--bg-primary': '#121212',
      '--bg-secondary': '#1e1e1e',
      '--bg-tertiary': '#2d2d2d',
      '--bg-content': '#0a0a0a',
      '--bg-accent-primary': '#dc143c',
      '--bg-accent-primary-hover': '#b21030',
      '--bg-success': '#3cb371',
      '--bg-error': '#ff4500',
      '--bg-warning': '#ffd700',
      '--text-primary': '#f5f5f5',
      '--text-secondary': '#d3d3d3',
      '--text-tertiary': '#a9a9a9',
      '--text-content-primary': '#f5f5f5',
      '--text-content-secondary': '#d3d3d3',
      '--text-on-accent': '#ffffff',
      '--text-success': '#3cb371',
      '--text-error': '#ff4500',
      '--text-warning': '#ffd700',
      '--border-primary': '#2d2d2d',
      '--border-secondary': '#444444',
      '--border-content': '#2d2d2d',
      '--scrollbar-track': '#1e1e1e',
      '--scrollbar-thumb': '#2d2d2d',
      '--scrollbar-thumb-hover': '#444444',
    },
  },
];
